/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Entidades.informacion_bancaria;
import Entidades.Empresa;
import Entidades.historial_creditos_extra;
import Factory.Factory;
import Procesos.BaseDatos;
import Procesos.EmpresaBD;
import Procesos.historial_creditos_extraBD;
import Procesos.informacion_bancariaBD;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class CompraCreditos extends javax.swing.JFrame {

    private static Factory factory;
    static ArrayList<informacion_bancaria> listaTarjetas;
    static Empresa empresa;

    /**
     * Creates new form CompraCreditos
     *
     * @param empresaObj
     */
    public CompraCreditos(Empresa empresaObj) {
        empresa = empresaObj;
        initComponents();
        this.setLocationRelativeTo(null);

        cargarListadoTarjetas();

    }

    private void cargarListadoTarjetas() {
        factory = new Factory();
        informacion_bancariaBD infoB_BD = factory.informacion_bancariaBD();

        listaTarjetas = infoB_BD.obtenerListadoByEmpresa(empresa.getId());

        this.cbox_metodoPago.removeAllItems();

        for (informacion_bancaria tarjeta : listaTarjetas) {
            String tarjetaFormated = tarjeta.getTipo_tarjeta() + " - XXXX " + tarjeta.getNumero_tarjeta().substring(12);
            this.cbox_metodoPago.addItem(tarjetaFormated);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frame_addMetodoPago = new javax.swing.JFrame();
        panel_title2 = new javax.swing.JPanel();
        lbl_title2 = new javax.swing.JLabel();
        panel_data2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_propietario = new javax.swing.JTextField();
        txt_numTarjeta = new javax.swing.JTextField();
        cbox_tipoTarjeta = new javax.swing.JComboBox<>();
        txt_fechaVencimiento = new javax.swing.JFormattedTextField();
        psw_codigoSeguridad = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtA_DireccionTarjeta = new javax.swing.JTextArea();
        btn_agregarMP = new javax.swing.JButton();
        btn_cancelarMP = new javax.swing.JButton();
        panel_data = new javax.swing.JPanel();
        lbl_empresa = new javax.swing.JLabel();
        lbl_cantidadCreditos = new javax.swing.JLabel();
        spn_cantidadCreditos = new javax.swing.JSpinner();
        lbl_metodoPago = new javax.swing.JLabel();
        cbox_metodoPago = new javax.swing.JComboBox<>();
        btn_addMetodoPago = new javax.swing.JButton();
        psw_codSeguridad = new javax.swing.JPasswordField();
        lbl_codSeguridad = new javax.swing.JLabel();
        btn_cancelar = new javax.swing.JButton();
        btn_aceptar = new javax.swing.JButton();
        panel_title = new javax.swing.JPanel();
        lbl_title = new javax.swing.JLabel();

        frame_addMetodoPago.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        frame_addMetodoPago.setTitle("Agregar Metodo de Pago");
        frame_addMetodoPago.setMinimumSize(new java.awt.Dimension(460, 560));
        frame_addMetodoPago.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                UpdateTarjetasCbox(evt);
            }
        });

        panel_title2.setBackground(new java.awt.Color(41, 98, 255));

        lbl_title2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_title2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_title2.setText("Agregar Metodo de Pago");

        javax.swing.GroupLayout panel_title2Layout = new javax.swing.GroupLayout(panel_title2);
        panel_title2.setLayout(panel_title2Layout);
        panel_title2Layout.setHorizontalGroup(
            panel_title2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_title2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_title2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_title2Layout.setVerticalGroup(
            panel_title2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_title2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lbl_title2)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        panel_data2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setText("Propietario");

        jLabel7.setText("Numero de la Tarjeta");

        jLabel8.setText("Tipo de Tarjeta");

        jLabel9.setText("Fecha de Vencimiento");

        jLabel10.setText("Codigo de Seguridad");

        jLabel11.setText("Dirección de la Tarjeta");

        cbox_tipoTarjeta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "VISA", "MasterCard", "American Express" }));

        txt_fechaVencimiento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM"))));
        txt_fechaVencimiento.setText("yyyy-MM");

        txtA_DireccionTarjeta.setColumns(20);
        txtA_DireccionTarjeta.setRows(3);
        jScrollPane1.setViewportView(txtA_DireccionTarjeta);

        btn_agregarMP.setText("Agregar");
        btn_agregarMP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarMPActionPerformed(evt);
            }
        });

        btn_cancelarMP.setText("Cancelar");
        btn_cancelarMP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarMPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_data2Layout = new javax.swing.GroupLayout(panel_data2);
        panel_data2.setLayout(panel_data2Layout);
        panel_data2Layout.setHorizontalGroup(
            panel_data2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_data2Layout.createSequentialGroup()
                .addGroup(panel_data2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_data2Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(btn_cancelarMP)
                        .addGap(83, 83, 83)
                        .addComponent(btn_agregarMP))
                    .addGroup(panel_data2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(panel_data2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(40, 40, 40)
                        .addGroup(panel_data2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_propietario)
                            .addComponent(txt_numTarjeta)
                            .addComponent(cbox_tipoTarjeta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_fechaVencimiento)
                            .addComponent(psw_codigoSeguridad)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        panel_data2Layout.setVerticalGroup(
            panel_data2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_data2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panel_data2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_propietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_data2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_numTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_data2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cbox_tipoTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_data2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_fechaVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_data2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(psw_codigoSeguridad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_data2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(panel_data2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_agregarMP)
                    .addComponent(btn_cancelarMP))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout frame_addMetodoPagoLayout = new javax.swing.GroupLayout(frame_addMetodoPago.getContentPane());
        frame_addMetodoPago.getContentPane().setLayout(frame_addMetodoPagoLayout);
        frame_addMetodoPagoLayout.setHorizontalGroup(
            frame_addMetodoPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_title2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel_data2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        frame_addMetodoPagoLayout.setVerticalGroup(
            frame_addMetodoPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frame_addMetodoPagoLayout.createSequentialGroup()
                .addComponent(panel_title2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_data2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Comprar Creditos");

        panel_data.setBackground(new java.awt.Color(255, 255, 255));

        lbl_empresa.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_empresa.setText("ProntoPBO");

        lbl_cantidadCreditos.setText("Cantidad de Creditos");

        spn_cantidadCreditos.setModel(new javax.swing.SpinnerNumberModel(5, 5, null, 5));

        lbl_metodoPago.setText("Metodo de pago");

        cbox_metodoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "VISA - xxxx XXXX" }));

        btn_addMetodoPago.setText("+");
        btn_addMetodoPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addMetodoPagoActionPerformed(evt);
            }
        });

        lbl_codSeguridad.setText("Codigo Seguridad");

        btn_cancelar.setText("Cancelar");

        btn_aceptar.setText("Aceptar");
        btn_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_dataLayout = new javax.swing.GroupLayout(panel_data);
        panel_data.setLayout(panel_dataLayout);
        panel_dataLayout.setHorizontalGroup(
            panel_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_dataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_dataLayout.createSequentialGroup()
                        .addComponent(lbl_empresa)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panel_dataLayout.createSequentialGroup()
                        .addGroup(panel_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_cantidadCreditos)
                            .addComponent(lbl_metodoPago)
                            .addComponent(lbl_codSeguridad))
                        .addGap(18, 18, 18)
                        .addGroup(panel_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(psw_codSeguridad)
                            .addComponent(spn_cantidadCreditos)
                            .addComponent(cbox_metodoPago, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_addMetodoPago)))
                .addContainerGap())
            .addGroup(panel_dataLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(btn_cancelar)
                .addGap(64, 64, 64)
                .addComponent(btn_aceptar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_dataLayout.setVerticalGroup(
            panel_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_dataLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(lbl_empresa)
                .addGap(18, 18, 18)
                .addGroup(panel_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_cantidadCreditos)
                    .addComponent(spn_cantidadCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_metodoPago)
                    .addComponent(cbox_metodoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_addMetodoPago))
                .addGap(18, 18, 18)
                .addGroup(panel_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(psw_codSeguridad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_codSeguridad))
                .addGap(35, 35, 35)
                .addGroup(panel_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cancelar)
                    .addComponent(btn_aceptar))
                .addGap(29, 29, 29))
        );

        panel_title.setBackground(new java.awt.Color(41, 98, 255));

        lbl_title.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_title.setForeground(new java.awt.Color(255, 255, 255));
        lbl_title.setText("Comprar Creditos");

        javax.swing.GroupLayout panel_titleLayout = new javax.swing.GroupLayout(panel_title);
        panel_title.setLayout(panel_titleLayout);
        panel_titleLayout.setHorizontalGroup(
            panel_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_titleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_title)
                .addContainerGap(229, Short.MAX_VALUE))
        );
        panel_titleLayout.setVerticalGroup(
            panel_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_titleLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lbl_title)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel_data, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panel_title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_data, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addMetodoPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addMetodoPagoActionPerformed
        this.frame_addMetodoPago.setVisible(true);
    }//GEN-LAST:event_btn_addMetodoPagoActionPerformed

    private void btn_agregarMPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarMPActionPerformed

        if (txt_propietario.getText().equals("") || txt_numTarjeta.getText().equals("")
                || txt_fechaVencimiento.getText().equals("") || String.valueOf(this.psw_codigoSeguridad.getPassword()).equals("") || txtA_DireccionTarjeta.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "No deje los campos vacios");
        } else {
            factory = new Factory();
            BaseDatos BD = factory.baseDatos();
            informacion_bancariaBD infBankBD = factory.informacion_bancariaBD();

            informacion_bancaria newInfoBank;

            String hashedCodSeg = BD.hashPassword(String.valueOf(this.psw_codigoSeguridad.getPassword()));

            String propietario = this.txt_propietario.getText();
            String numero_tarjeta = this.txt_numTarjeta.getText();
            String tipo_tarjeta = this.cbox_tipoTarjeta.getItemAt(this.cbox_tipoTarjeta.getSelectedIndex());
            String fecha_vencimiento = this.txt_fechaVencimiento.getText();
            String codigo_seguridad = hashedCodSeg;
            String direccion_tarjeta = this.txtA_DireccionTarjeta.getText();
            int empresa_id = empresa.getId();

            newInfoBank = factory.informacion_bancaria(0, propietario, numero_tarjeta, tipo_tarjeta, fecha_vencimiento, codigo_seguridad, direccion_tarjeta, empresa_id);

            infBankBD.insertarInformacionBancaria(newInfoBank);
        }
    }//GEN-LAST:event_btn_agregarMPActionPerformed

    private void btn_cancelarMPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarMPActionPerformed
        this.frame_addMetodoPago.dispose();
    }//GEN-LAST:event_btn_cancelarMPActionPerformed

    private void UpdateTarjetasCbox(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_UpdateTarjetasCbox
        System.out.println("Actualizando Listado");
        cargarListadoTarjetas();
    }//GEN-LAST:event_UpdateTarjetasCbox

    private void btn_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptarActionPerformed
        String codigoIngresado = String.valueOf(this.psw_codSeguridad.getPassword());
        if (codigoIngresado.equals("")) {
            JOptionPane.showMessageDialog(null, "No deje los campos vacios");
        } else {
            factory = new Factory();
            BaseDatos BD = factory.baseDatos();
            historial_creditos_extraBD creditosBD = factory.historial_creditos_extraBD();
            EmpresaBD empresaBD = factory.empresaBD();

            String HashedCode = listaTarjetas.get(this.cbox_metodoPago.getSelectedIndex()).getCodigo_seguridad();

            if (BD.checkPassword(codigoIngresado, HashedCode) == true) {
                int cantidad_creditos = (Integer) this.spn_cantidadCreditos.getValue();
                double total = cantidad_creditos;
                int metodo_pago_id = listaTarjetas.get(this.cbox_metodoPago.getSelectedIndex()).getId();
                historial_creditos_extra HistoCred = factory.historial_creditos_extra('0', empresa.getId(), " ", cantidad_creditos, total, metodo_pago_id);

                boolean flag1 = creditosBD.guardarCreditosExtra(HistoCred);
                boolean flag2 = empresaBD.agregarCreditosExtra(empresa.getId(), cantidad_creditos);

                if (flag1 == true && flag2 == true) {
                    JOptionPane.showMessageDialog(null, "Nuevo registro agregado correctamente");
                } else {
                    JOptionPane.showMessageDialog(null, "Ha ocurrido un error al actualizar el registro");
                }

            } else {
                JOptionPane.showMessageDialog(null, "El codigo de seguridad no es correcto");
            }

        }
    }//GEN-LAST:event_btn_aceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompraCreditos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompraCreditos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompraCreditos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompraCreditos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CompraCreditos(empresa).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_aceptar;
    private javax.swing.JButton btn_addMetodoPago;
    private javax.swing.JButton btn_agregarMP;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_cancelarMP;
    private javax.swing.JComboBox<String> cbox_metodoPago;
    private javax.swing.JComboBox<String> cbox_tipoTarjeta;
    private javax.swing.JFrame frame_addMetodoPago;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_cantidadCreditos;
    private javax.swing.JLabel lbl_codSeguridad;
    private javax.swing.JLabel lbl_empresa;
    private javax.swing.JLabel lbl_metodoPago;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JLabel lbl_title2;
    private javax.swing.JPanel panel_data;
    private javax.swing.JPanel panel_data2;
    private javax.swing.JPanel panel_title;
    private javax.swing.JPanel panel_title2;
    private javax.swing.JPasswordField psw_codSeguridad;
    private javax.swing.JPasswordField psw_codigoSeguridad;
    private javax.swing.JSpinner spn_cantidadCreditos;
    private javax.swing.JTextArea txtA_DireccionTarjeta;
    private javax.swing.JFormattedTextField txt_fechaVencimiento;
    private javax.swing.JTextField txt_numTarjeta;
    private javax.swing.JTextField txt_propietario;
    // End of variables declaration//GEN-END:variables
}
