/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Entidades.hr_applicant;
import Factory.Factory;
import Procesos.BaseDatos;
import java.util.ArrayList;

/**
 *
 * @author malte
 */
public class InformacionEmpleado extends javax.swing.JFrame {
    
    private static Factory factory;
    /**
     * Creates new form InformacionEmpleado
     */
    public InformacionEmpleado() {
        initComponents();
        factory = new Factory();
        this.setLocationRelativeTo(null);
        
        BaseDatos BD = factory.baseDatos();
        BD.obtenerAspirantes();
        ArrayList<hr_applicant> listaAspirantes = BD.obtenerAspirantes();
        
        hr_applicant solicitante = listaAspirantes.get(factory.principal().ID - 1);
        
        int id = solicitante.getId();
        int campaign_id = solicitante.getCampaign_id();
        int source_id = solicitante.getSource_id();
        int medium_id = solicitante.getMedium_id();
        String email = solicitante.getEmail_cc();
        
        boolean activade = solicitante.isActive();
        String description = solicitante.getDescription();
        String email_From = solicitante.getEmail_from();
        Double pro = solicitante.getProbability();
        int partner_id = solicitante.getPartner_id();
        String create_date = solicitante.getCreate_date();
        int stage_id = solicitante.getStage_id();
        int last_stage_id = solicitante.getLast_stage_id();
        int company_id = solicitante.getCompany_id();
        int user_id = solicitante.getUser_id();
        String date_closed = solicitante.getDate_closed();
        String date_open = solicitante.getDate_open();
        String date_last_stage_update = solicitante.getDate_last_stage_update();
        String priority = solicitante.getPriority();
        int job_id = solicitante.getJob_id();
        Double salary_proposed = solicitante.getSalary_proposed();
        Double salary_expected = solicitante.getSalary_expected();
        String availability = solicitante.getAvailability();
        String partner_name = solicitante.getPartner_name();
        String partner_mobile = solicitante.getPartner_mobile();
        String partner_phone = solicitante.getPartner_phone();
        
        this.nameLB.setText(partner_name);
        this.desLB.setText(description);
        this.sal_e.setText(salary_expected.toString());
        this.sal_p.setText(salary_proposed.toString());
        this.priLB.setText(priority);
        this.proLB.setText(pro.toString());
        this.actiLB.setText(String.valueOf(activade));
        this.phoneLB.setText(partner_mobile);
        this.numberLB.setText(partner_phone);
        this.emailLB.setText(email);
        this.dateCLB.setText(create_date);
        this.avaLB.setText(availability);
        this.messageLB.setText(date_last_stage_update);
        this.jobIDLB.setText(String.valueOf(job_id));
        this.solLB.setText(String.valueOf(id));
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_top = new javax.swing.JPanel();
        lbl_title1 = new javax.swing.JLabel();
        nombre_LB = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        nameLB = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        desLB = new javax.swing.JLabel();
        sal_e = new javax.swing.JLabel();
        sal_p = new javax.swing.JLabel();
        priLB = new javax.swing.JLabel();
        proLB = new javax.swing.JLabel();
        actiLB = new javax.swing.JLabel();
        phoneLB = new javax.swing.JLabel();
        numberLB = new javax.swing.JLabel();
        emailLB = new javax.swing.JLabel();
        dateCLB = new javax.swing.JLabel();
        avaLB = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        messageLB = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jobIDLB = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        solLB = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                formFocusLost(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        panel_top.setBackground(new java.awt.Color(41, 98, 255));

        lbl_title1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_title1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_title1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_title1.setText("Informacion del recurso humano");

        javax.swing.GroupLayout panel_topLayout = new javax.swing.GroupLayout(panel_top);
        panel_top.setLayout(panel_topLayout);
        panel_topLayout.setHorizontalGroup(
            panel_topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_topLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_title1)
                .addGap(190, 190, 190))
        );
        panel_topLayout.setVerticalGroup(
            panel_topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_topLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lbl_title1)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        nombre_LB.setText("Nombre:");

        jButton1.setText("Atras");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        nameLB.setText("name");

        jLabel1.setText("Descripcion");

        desLB.setText("jLabel2");

        sal_e.setText("jLabel2");

        sal_p.setText("jLabel2");

        priLB.setText("jLabel2");

        proLB.setText("jLabel2");

        actiLB.setText("jLabel2");

        phoneLB.setText("jLabel2");

        numberLB.setText("jLabel3");

        emailLB.setText("jLabel2");

        dateCLB.setText("jLabel2");

        avaLB.setText("jLabel2");

        jLabel2.setText("Salario esperado:");

        jLabel3.setText("Salario propuesto:");

        jLabel4.setText("Prioridad:");

        jLabel5.setText("Probabilidad:");

        jLabel6.setText("Activo:");

        jLabel7.setText("Telefono celular:");

        jLabel8.setText("Telefono fijo:");

        jLabel9.setText("Email:");

        jLabel10.setText("Fecha de ingreso al sistema:");

        jLabel11.setText("Disponible a partir de:");

        messageLB.setText("jLabel12");

        jLabel12.setText("Ultima fecha de actualizacion:");

        jLabel13.setText("Trabajo a aplicar ID");

        jobIDLB.setText("jLabel1");

        jLabel14.setText("ID del solicitante:");

        solLB.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_top, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(271, 271, 271)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(nombre_LB)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailLB)
                    .addComponent(numberLB)
                    .addComponent(sal_e)
                    .addComponent(desLB)
                    .addComponent(sal_p)
                    .addComponent(priLB)
                    .addComponent(proLB)
                    .addComponent(actiLB)
                    .addComponent(phoneLB)
                    .addComponent(nameLB))
                .addGap(0, 176, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14))
                                .addGap(78, 78, 78)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jobIDLB)
                                    .addComponent(solLB))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 1, Short.MAX_VALUE)
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(avaLB)
                                    .addComponent(messageLB)
                                    .addComponent(dateCLB))))
                        .addGap(115, 115, 115))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_top, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre_LB)
                    .addComponent(nameLB)
                    .addComponent(dateCLB)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(desLB)
                    .addComponent(avaLB)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sal_e)
                    .addComponent(jLabel2)
                    .addComponent(messageLB)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sal_p)
                    .addComponent(jLabel3)
                    .addComponent(jLabel13)
                    .addComponent(jobIDLB))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priLB)
                    .addComponent(jLabel4)
                    .addComponent(jLabel14)
                    .addComponent(solLB))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(proLB)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(actiLB)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneLB)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numberLB)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLB)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusLost
        this.setVisible(false);
    }//GEN-LAST:event_formFocusLost

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_formMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformacionEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformacionEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformacionEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformacionEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InformacionEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel actiLB;
    private javax.swing.JLabel avaLB;
    private javax.swing.JLabel dateCLB;
    private javax.swing.JLabel desLB;
    private javax.swing.JLabel emailLB;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jobIDLB;
    private javax.swing.JLabel lbl_title1;
    private javax.swing.JLabel messageLB;
    private javax.swing.JLabel nameLB;
    private javax.swing.JLabel nombre_LB;
    private javax.swing.JLabel numberLB;
    private javax.swing.JPanel panel_top;
    private javax.swing.JLabel phoneLB;
    private javax.swing.JLabel priLB;
    private javax.swing.JLabel proLB;
    private javax.swing.JLabel sal_e;
    private javax.swing.JLabel sal_p;
    private javax.swing.JLabel solLB;
    // End of variables declaration//GEN-END:variables
}
