/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Entidades.Empresa;
import Entidades.Usuario;
import Entidades.hr_applicant;
import Entidades.informacion_bancaria;
import Factory.Factory;
import Procesos.BaseDatos;
import Procesos.EmpresaBD;
import Procesos.informacion_bancariaBD;
import java.sql.Date;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class Principal extends javax.swing.JFrame {

    private static Factory factory;
    static ArrayList<informacion_bancaria> listaTarjetas;
    public static int ID;
    static Usuario user;
    static Empresa empresa;

    /**
     * Creates new form Principal
     *
     * @param usuario
     */
    public Principal(Usuario usuario) {
        user = usuario;
        factory = new Factory();
        EmpresaBD EmpBD = factory.empresaBD();

        empresa = EmpBD.obtenerEmpresaByID(usuario.getEmpresa());

        initComponents();
        this.setLocationRelativeTo(null);
        cargarColumnasTabla();

        BaseDatos BD = factory.baseDatos();
        BD.obtenerAspirantes();
        cargarModeloTabla();

        mbtn_nuevoUsuario.setVisible(false);
        mbtn_nuevaEmpresa.setVisible(false);

        this.lbl_usuario.setText(user.getNombres() + " " + user.getApellidos()
                + " - " + user.getRol() + " - " + empresa.getNombre_empresa());

        this.lbl_creditos.setText("Creditos base: " + empresa.getCreditos_base() + " Creditos extra: " + empresa.getCreditos_extra());

        if (user.getRol().equals("SUPER_ADMIN")) {
            mbtn_nuevoUsuario.setVisible(true);
            mbtn_nuevoUsuario.setEnabled(true);

            mbtn_nuevaEmpresa.setVisible(true);
            mbtn_nuevaEmpresa.setEnabled(true);
        }

        cargarListadoTarjetas();

    }

    private void cargarListadoTarjetas() {
        factory = new Factory();
        informacion_bancariaBD infoB_BD = factory.informacion_bancariaBD();

        listaTarjetas = infoB_BD.obtenerListadoByEmpresa(empresa.getId());
        this.cbox_metodoPago.removeAllItems();
        for (informacion_bancaria tarjeta : listaTarjetas) {
            String tarjetaFormated = tarjeta.getTipo_tarjeta() + " - XXXX " + tarjeta.getNumero_tarjeta().substring(12);
            this.cbox_metodoPago.addItem(tarjetaFormated);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frame_suscripcion = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        lbl_title = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbox_tipoSus = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cbox_metodoPago = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        btn_aceptarSus = new javax.swing.JButton();
        btn_cancelarSus = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panel_infoUsuario = new javax.swing.JPanel();
        lbl_usuario = new javax.swing.JLabel();
        lbl_creditos = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btn_cargarAspirantes = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        panel_busqueda = new javax.swing.JPanel();
        lbl_busqueda = new javax.swing.JLabel();
        txt_busqueda = new javax.swing.JTextField();
        btn_buscar = new javax.swing.JButton();
        cbox_criterio = new javax.swing.JComboBox<>();
        lbl_criterio = new javax.swing.JLabel();
        tbtn_comprado = new javax.swing.JToggleButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_archivo = new javax.swing.JMenu();
        mbtn_nuevoUsuario = new javax.swing.JMenuItem();
        mbtn_nuevaEmpresa = new javax.swing.JMenuItem();
        mbtn_salir = new javax.swing.JMenuItem();
        menu_creditos = new javax.swing.JMenu();
        mbtn_adminSuscripcion = new javax.swing.JMenuItem();
        mbtn_agregarCreditos = new javax.swing.JMenuItem();
        menu_ayuda = new javax.swing.JMenu();
        mbtn_acercaDe = new javax.swing.JMenuItem();

        frame_suscripcion.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        frame_suscripcion.setTitle("Administrar Suscripción");
        frame_suscripcion.setMinimumSize(new java.awt.Dimension(400, 300));

        jPanel3.setBackground(new java.awt.Color(41, 98, 255));

        lbl_title.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_title.setForeground(new java.awt.Color(255, 255, 255));
        lbl_title.setText("Administrar Suscripción");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_title)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lbl_title)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Tipo Suscripción");

        cbox_tipoSus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Socio Básico", "Socio Preferencial", "Socio Gold", "Anular Suscripción" }));

        jLabel3.setText("Método de Pago");

        cbox_metodoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Total: $00.00 USD");

        btn_aceptarSus.setText("Aceptar");
        btn_aceptarSus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptarSusActionPerformed(evt);
            }
        });

        btn_cancelarSus.setText("Cancelar");
        btn_cancelarSus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarSusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel4))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbox_tipoSus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbox_metodoPago, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_cancelarSus)
                .addGap(100, 100, 100)
                .addComponent(btn_aceptarSus)
                .addGap(71, 71, 71))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbox_tipoSus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbox_metodoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_aceptarSus)
                    .addComponent(btn_cancelarSus))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout frame_suscripcionLayout = new javax.swing.GroupLayout(frame_suscripcion.getContentPane());
        frame_suscripcion.getContentPane().setLayout(frame_suscripcionLayout);
        frame_suscripcionLayout.setHorizontalGroup(
            frame_suscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        frame_suscripcionLayout.setVerticalGroup(
            frame_suscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frame_suscripcionLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ProntoBPO - Perfiles Laborales");

        jPanel1.setBackground(new java.awt.Color(41, 98, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Listado de Aspirantes");

        panel_infoUsuario.setBackground(new java.awt.Color(41, 98, 255));

        lbl_usuario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_usuario.setText("Roberto Acevedo - Administrador - ProntoPBO");

        lbl_creditos.setForeground(new java.awt.Color(255, 255, 255));
        lbl_creditos.setText("Creditos Restantes: 25");

        javax.swing.GroupLayout panel_infoUsuarioLayout = new javax.swing.GroupLayout(panel_infoUsuario);
        panel_infoUsuario.setLayout(panel_infoUsuarioLayout);
        panel_infoUsuarioLayout.setHorizontalGroup(
            panel_infoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_infoUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_infoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_usuario)
                    .addComponent(lbl_creditos))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_infoUsuarioLayout.setVerticalGroup(
            panel_infoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_infoUsuarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_usuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_creditos)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panel_infoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_infoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btn_cargarAspirantes.setText("Cargar Aspirantes");
        btn_cargarAspirantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cargarAspirantesActionPerformed(evt);
            }
        });

        jTable1.setModel(modeloTabla);
        jTable1.setDoubleBuffered(true);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        panel_busqueda.setBackground(new java.awt.Color(255, 255, 255));

        lbl_busqueda.setText("Buscar");

        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        cbox_criterio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nombre", "Descripción", "Salario Esperado" }));

        lbl_criterio.setText("Criterio de busqueda");

        tbtn_comprado.setText("Comprado");

        javax.swing.GroupLayout panel_busquedaLayout = new javax.swing.GroupLayout(panel_busqueda);
        panel_busqueda.setLayout(panel_busquedaLayout);
        panel_busquedaLayout.setHorizontalGroup(
            panel_busquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_busquedaLayout.createSequentialGroup()
                .addGap(0, 100, Short.MAX_VALUE)
                .addGroup(panel_busquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_busqueda, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_criterio, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_busquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbox_criterio, 0, 180, Short.MAX_VALUE)
                    .addComponent(txt_busqueda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_busquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_buscar)
                    .addComponent(tbtn_comprado)))
        );
        panel_busquedaLayout.setVerticalGroup(
            panel_busquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_busquedaLayout.createSequentialGroup()
                .addGap(0, 13, Short.MAX_VALUE)
                .addGroup(panel_busquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbox_criterio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbtn_comprado)
                    .addComponent(lbl_criterio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_busquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscar)
                    .addComponent(lbl_busqueda)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 988, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_cargarAspirantes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panel_busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_cargarAspirantes)
                    .addComponent(panel_busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
                .addContainerGap())
        );

        menu_archivo.setText("Archivo");

        mbtn_nuevoUsuario.setText("Añadir Usuario");
        mbtn_nuevoUsuario.setEnabled(false);
        mbtn_nuevoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbtn_nuevoUsuarioActionPerformed(evt);
            }
        });
        menu_archivo.add(mbtn_nuevoUsuario);

        mbtn_nuevaEmpresa.setText("Añadir Empresa");
        mbtn_nuevaEmpresa.setEnabled(false);
        mbtn_nuevaEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbtn_nuevaEmpresaActionPerformed(evt);
            }
        });
        menu_archivo.add(mbtn_nuevaEmpresa);

        mbtn_salir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        mbtn_salir.setText("Salir");
        mbtn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbtn_salirActionPerformed(evt);
            }
        });
        menu_archivo.add(mbtn_salir);

        jMenuBar1.add(menu_archivo);

        menu_creditos.setText("Creditos");

        mbtn_adminSuscripcion.setText("Administrar Suscripción");
        mbtn_adminSuscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbtn_adminSuscripcionActionPerformed(evt);
            }
        });
        menu_creditos.add(mbtn_adminSuscripcion);

        mbtn_agregarCreditos.setText("Agregar Creditos");
        mbtn_agregarCreditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbtn_agregarCreditosActionPerformed(evt);
            }
        });
        menu_creditos.add(mbtn_agregarCreditos);

        jMenuBar1.add(menu_creditos);

        menu_ayuda.setText("Ayuda");

        mbtn_acercaDe.setText("Acerca de");
        menu_ayuda.add(mbtn_acercaDe);

        jMenuBar1.add(menu_ayuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cargarAspirantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cargarAspirantesActionPerformed
        BaseDatos BD = factory.baseDatos();
        BD.obtenerAspirantes();
        cargarModeloTabla();
    }//GEN-LAST:event_btn_cargarAspirantesActionPerformed

    private void mbtn_nuevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbtn_nuevoUsuarioActionPerformed
        // TODO add your handling code here:
        RegistroUsuario reg_usu = factory.reg_user();
        reg_usu.setVisible(true);
    }//GEN-LAST:event_mbtn_nuevoUsuarioActionPerformed

    private void mbtn_nuevaEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbtn_nuevaEmpresaActionPerformed
        // TODO add your handling code here:
        RegistroEmpresa reg_emp = factory.reg_empre();
        reg_emp.setVisible(true);
    }//GEN-LAST:event_mbtn_nuevaEmpresaActionPerformed

    private void mbtn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbtn_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mbtn_salirActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int selec = jTable1.rowAtPoint(evt.getPoint());
        int ID = jTable1.getSelectedRow();

        System.out.print(ID);

        PerfilSolicitud perfilSolicitud = factory.perfilSolicitud();
        perfilSolicitud.index = ID;
        perfilSolicitud.setVisible(true);
    }//GEN-LAST:event_jTable1MouseClicked

    private void mbtn_agregarCreditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbtn_agregarCreditosActionPerformed
        CompraCreditos compraCreditos = factory.compraCreditos(empresa);
        compraCreditos.setVisible(true);
    }//GEN-LAST:event_mbtn_agregarCreditosActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        String busqueda = this.txt_busqueda.getText();

        BaseDatos BD = factory.baseDatos();
        int optionSelected = this.cbox_criterio.getSelectedIndex();

        switch (optionSelected) {
            case 0:
                cargarListadoTabla(BD.buscarAspirantesByName(busqueda));
                break;
            case 1:
                cargarListadoTabla(BD.buscarAspirantesByDescripcion(busqueda));
                break;
            case 2:
                cargarListadoTabla(BD.buscarAspirantesBySalarioEsperado(Double.valueOf(busqueda)));
                break;
            default:
            // code block
        }


    }//GEN-LAST:event_btn_buscarActionPerformed

    private void mbtn_adminSuscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbtn_adminSuscripcionActionPerformed
        this.frame_suscripcion.setVisible(true);
    }//GEN-LAST:event_mbtn_adminSuscripcionActionPerformed

    private void btn_aceptarSusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptarSusActionPerformed
        int empresa_id = empresa.getId();
        Date fecha_inicio;
        Date fecha_final;
        String tipo_suscripcion = "";
        Double total;
        int metodo_pago_id;
        int cantidad_creditos = 0;

        switch (this.cbox_tipoSus.getSelectedIndex()) {
            case 0:
                tipo_suscripcion = "BASIC_SUSCRIPTION";
                cantidad_creditos = 75;
                break;
            case 1:
                tipo_suscripcion = "PREFERENTIAL_SUSCRIPTION";
                cantidad_creditos = 125;
                break;
            case 2:
                tipo_suscripcion = "GOLD_SUSCRIPTION";
                cantidad_creditos = 999999;
                break;
            case 3:
                tipo_suscripcion = "NULA";
                cantidad_creditos = 0;
                break;
            default:
                break;
        }

        factory = new Factory();
        EmpresaBD empresaBD = factory.empresaBD();

        int consulta = empresaBD.actualizarSuscripcion(empresa_id, tipo_suscripcion, cantidad_creditos);

        if (consulta != 1) {
            JOptionPane.showMessageDialog(null, "Los datos se han guardado correctamente",
                    "Éxito en la operación", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Los datos no se pudieron guardar\n"
                    + "Inténtelo nuevamente", "Error en la operación", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_aceptarSusActionPerformed

    private void btn_cancelarSusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarSusActionPerformed
        this.frame_suscripcion.dispose();
    }//GEN-LAST:event_btn_cancelarSusActionPerformed

    DefaultTableModel modeloTabla = new DefaultTableModel();

    private void cargarColumnasTabla() {
        modeloTabla.addColumn("ID");
        modeloTabla.addColumn("Nombre");
        modeloTabla.addColumn("Descripcion");
        modeloTabla.addColumn("Trabajo Solicitado");
        modeloTabla.addColumn("Salario Esperado");
    }

    private void cargarModeloTabla() {
        BaseDatos BD = factory.baseDatos();
        cargarListadoTabla(BD.obtenerAspirantes());

    }

    private void cargarListadoTabla(ArrayList<hr_applicant> listaAspirantes) {
        int cantidadAspirantes = listaAspirantes.size();
        modeloTabla.setNumRows(cantidadAspirantes);

        for (int i = 0; i < cantidadAspirantes; i++) {
            hr_applicant solicitante = listaAspirantes.get(i);

            int id = solicitante.getId();
            String partner_name = solicitante.getPartner_name();
            String description = solicitante.getDescription();
            int job_id = solicitante.getJob_id();
            Double salary_expected = solicitante.getSalary_expected();

            modeloTabla.setValueAt(id, i, 0);
            modeloTabla.setValueAt(partner_name, i, 1);
            modeloTabla.setValueAt(description, i, 2);
            modeloTabla.setValueAt(job_id, i, 3);
            modeloTabla.setValueAt(salary_expected, i, 4);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal(user).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_aceptarSus;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_cancelarSus;
    private javax.swing.JButton btn_cargarAspirantes;
    private javax.swing.JComboBox<String> cbox_criterio;
    private javax.swing.JComboBox<String> cbox_metodoPago;
    private javax.swing.JComboBox<String> cbox_tipoSus;
    private javax.swing.JFrame frame_suscripcion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_busqueda;
    private javax.swing.JLabel lbl_creditos;
    private javax.swing.JLabel lbl_criterio;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JLabel lbl_usuario;
    private javax.swing.JMenuItem mbtn_acercaDe;
    private javax.swing.JMenuItem mbtn_adminSuscripcion;
    private javax.swing.JMenuItem mbtn_agregarCreditos;
    public javax.swing.JMenuItem mbtn_nuevaEmpresa;
    public javax.swing.JMenuItem mbtn_nuevoUsuario;
    private javax.swing.JMenuItem mbtn_salir;
    private javax.swing.JMenu menu_archivo;
    private javax.swing.JMenu menu_ayuda;
    private javax.swing.JMenu menu_creditos;
    private javax.swing.JPanel panel_busqueda;
    private javax.swing.JPanel panel_infoUsuario;
    private javax.swing.JToggleButton tbtn_comprado;
    private javax.swing.JTextField txt_busqueda;
    // End of variables declaration//GEN-END:variables
}
