/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Entidades.Empresa;
import Factory.Factory;
import Procesos.EmpresaBD;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class RegistroEmpresa extends javax.swing.JFrame {

    private static Factory factory;

    /**
     * Creates new form RegistroEmpresa
     */
    public RegistroEmpresa() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_top12 = new javax.swing.JPanel();
        lbl_title13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbl_nombreEmpresa = new javax.swing.JLabel();
        lbl_formaJuridica = new javax.swing.JLabel();
        lbl_fechaConstitucion = new javax.swing.JLabel();
        lbl_direccion = new javax.swing.JLabel();
        lbl_correo = new javax.swing.JLabel();
        lbl_numRegistro = new javax.swing.JLabel();
        lbl_resumenNegocio = new javax.swing.JLabel();
        lbl_sectorActividad = new javax.swing.JLabel();
        lbl_dueno = new javax.swing.JLabel();
        lbl_telefono = new javax.swing.JLabel();
        txt_dueno = new javax.swing.JTextField();
        txt_sectorActividad = new javax.swing.JTextField();
        txt_numRegistro = new javax.swing.JTextField();
        txt_correo = new javax.swing.JTextField();
        txt_formaJuridica = new javax.swing.JTextField();
        txt_nombreEmpresa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_resumenNegocio = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_direccion = new javax.swing.JTextArea();
        btn_aceptar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        txt_fechaConstitucion = new javax.swing.JFormattedTextField();
        txt_telefono = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panel_top12.setBackground(new java.awt.Color(41, 98, 255));

        lbl_title13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_title13.setForeground(new java.awt.Color(255, 255, 255));
        lbl_title13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_title13.setText("Registrar Empresa");

        javax.swing.GroupLayout panel_top12Layout = new javax.swing.GroupLayout(panel_top12);
        panel_top12.setLayout(panel_top12Layout);
        panel_top12Layout.setHorizontalGroup(
            panel_top12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_top12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_title13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_top12Layout.setVerticalGroup(
            panel_top12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_top12Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lbl_title13)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lbl_nombreEmpresa.setText("Nombre de la Empresa");

        lbl_formaJuridica.setText("Forma Juridica");

        lbl_fechaConstitucion.setText("Fecha de Constitución");

        lbl_direccion.setText("Dirección");

        lbl_correo.setText("Correo");

        lbl_numRegistro.setText("Numero de Registro");

        lbl_resumenNegocio.setText("Resumen del Negocio");

        lbl_sectorActividad.setText("Sector de Actividad");

        lbl_dueno.setText("Dueño");

        lbl_telefono.setText("Telefono");

        txt_resumenNegocio.setColumns(20);
        txt_resumenNegocio.setRows(3);
        jScrollPane1.setViewportView(txt_resumenNegocio);

        txt_direccion.setColumns(20);
        txt_direccion.setRows(3);
        jScrollPane2.setViewportView(txt_direccion);

        btn_aceptar.setText("Aceptar");
        btn_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptarActionPerformed(evt);
            }
        });

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        txt_fechaConstitucion.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("d/MM/yyyy"))));
        txt_fechaConstitucion.setText("DD/MM/YYYY");

        try {
            txt_telefono.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl_correo)
                                    .addComponent(lbl_direccion)
                                    .addComponent(lbl_numRegistro)
                                    .addComponent(lbl_telefono)
                                    .addComponent(lbl_dueno)
                                    .addComponent(lbl_sectorActividad)
                                    .addComponent(lbl_resumenNegocio)
                                    .addComponent(lbl_fechaConstitucion)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl_nombreEmpresa)
                                    .addComponent(lbl_formaJuridica))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_nombreEmpresa)
                            .addComponent(txt_formaJuridica)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                            .addComponent(txt_correo)
                            .addComponent(txt_numRegistro)
                            .addComponent(txt_dueno)
                            .addComponent(txt_sectorActividad)
                            .addComponent(jScrollPane1)
                            .addComponent(txt_fechaConstitucion)
                            .addComponent(txt_telefono)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(btn_cancelar)
                        .addGap(51, 51, 51)
                        .addComponent(btn_aceptar)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nombreEmpresa)
                    .addComponent(txt_nombreEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_formaJuridica)
                    .addComponent(txt_formaJuridica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_fechaConstitucion)
                    .addComponent(txt_fechaConstitucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_direccion)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_correo))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_numRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_numRegistro))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_telefono)
                    .addComponent(txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_dueno)
                    .addComponent(txt_dueno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_sectorActividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_sectorActividad))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_resumenNegocio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_aceptar)
                    .addComponent(btn_cancelar))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_top12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_top12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptarActionPerformed
        // TODO add your handling code here:
        String nombreEmpresa = this.txt_nombreEmpresa.getText();
        String formaJuridica = this.txt_formaJuridica.getText();
        String fecha = this.txt_fechaConstitucion.getText();
        String direccion = this.txt_direccion.getText();
        String correo = this.txt_correo.getText();
        String numRegistro = this.txt_numRegistro.getText();
        int tel = Integer.valueOf(this.txt_telefono.getText());
        String dueno = this.txt_dueno.getText();
        String sector = this.txt_sectorActividad.getText();
        String resumen = this.txt_resumenNegocio.getText();

        if (!nombreEmpresa.equals("") && !formaJuridica.equals("") && !fecha.equals("") && !direccion.equals("")
                && !correo.equals("") && !numRegistro.equals("") && !this.txt_telefono.getText().equals("") && !dueno.equals("") && !sector.equals("") && !resumen.equals("")) {
            factory = new Factory();
            Empresa empresa = factory.empresa(0, nombreEmpresa, formaJuridica, fecha, direccion, correo, numRegistro, tel, dueno, sector, resumen, 0, 0, 0, "NULO");

            EmpresaBD empresaBD = factory.empresaBD();

            int consulta = empresaBD.registrarUsuarioNuevo(empresa);

            if (consulta > 0) {
                JOptionPane.showMessageDialog(null, "Los datos se han guardado correctamente",
                        "Éxito en la operación", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Los datos no se pudieron guardar\n"
                        + "Inténtelo nuevamente", "Error en la operación", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "No deje los campos vacios");
        }
    }//GEN-LAST:event_btn_aceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroEmpresa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_aceptar;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_correo;
    private javax.swing.JLabel lbl_direccion;
    private javax.swing.JLabel lbl_dueno;
    private javax.swing.JLabel lbl_fechaConstitucion;
    private javax.swing.JLabel lbl_formaJuridica;
    private javax.swing.JLabel lbl_nombreEmpresa;
    private javax.swing.JLabel lbl_numRegistro;
    private javax.swing.JLabel lbl_resumenNegocio;
    private javax.swing.JLabel lbl_sectorActividad;
    private javax.swing.JLabel lbl_telefono;
    private javax.swing.JLabel lbl_title13;
    private javax.swing.JPanel panel_top12;
    private javax.swing.JTextField txt_correo;
    private javax.swing.JTextArea txt_direccion;
    private javax.swing.JTextField txt_dueno;
    private javax.swing.JFormattedTextField txt_fechaConstitucion;
    private javax.swing.JTextField txt_formaJuridica;
    private javax.swing.JTextField txt_nombreEmpresa;
    private javax.swing.JTextField txt_numRegistro;
    private javax.swing.JTextArea txt_resumenNegocio;
    private javax.swing.JTextField txt_sectorActividad;
    private javax.swing.JFormattedTextField txt_telefono;
    // End of variables declaration//GEN-END:variables
}
